version: 0.2

phases:
    build:
      commands:
        - echo Entered the build phase
        - mvn clean package
    post_build:
        - echo build completed successfully
artifacts:
  files:
    - target/test.jar
  discard-path: yes
